---
abstract: 'Create get and set methods and simplify object initialization'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Hash::AutoHash::Args: 1.16
  IO::Scalar: 2.11
  Module::Build: 0.4007
  Test::Deep: 0.11
  Test::More: 0.98
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-AutoClass
provides:
  Class::AutoClass:
    file: lib/Class/AutoClass.pm
    version: 1.56_01
  Class::AutoClass::Root:
    file: lib/Class/AutoClass/Root.pm
    version: 1
requires:
  Cwd: 3.4
  File::Spec: 3.4
  Hash::AutoHash: 1.16
  Hash::AutoHash::Args: 1.16
  IO::Scalar: 2.11
  List::MoreUtils: 0.33
  Tie::ToObject: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 1.56_01
