# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-AutoClass
version:      0.091
version_from: lib/Class/AutoClass.pm
installdirs:  site
requires:
    Storable:                      IO::Scalar
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
