---
abstract: 'Create get and set methods and simplify object initialization'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Exporter: 0
  IO::Scalar: 2.1
  Scalar::Util: 1.01
  Test::Deep: 0.098
  Test::More: 0.88
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-AutoClass
provides:
  Class::AutoClass:
    file: lib/Class/AutoClass.pm
    version: 1.55
  Class::AutoClass::Root:
    file: lib/Class/AutoClass/Root.pm
    version: 1
requires:
  Carp: 0
  Hash::AutoHash::Args: 1.1
  Storable: 2.16
resources:
  license: http://dev.perl.org/licenses/
version: 1.55
