#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-AutoClass
version:      0.092
version_from: lib/Class/AutoClass.pm
installdirs:  site
requires:
    Test::More:                    0
    IO::Scalar:                    0
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
